spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  messages:
    always-use-message-format: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8181
  error:
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
